### ISSUE TITLE
[Feat] Update README.md

### ISSUE THREAD

**Issue by dlwlehd** [alsdn1360/exercise_issue#4]
**해당 기능을 한문장으로 묘사해주세요.**

코드트리 실력진단 결과가 빠져있어 추가를 진행합니다.

**예상되는 Tasklist**

- [x] 실력진단 응시
- [x] 프로필의 실력진단 결과 README.md 에 추가

**Comment by alsdn1360** [comment]
뭐야 이거 왜 너도 가능하세요?

**Comment by alsdn1360** [comment]
실력이 여전합니다 ㅎㅎ
